// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApi.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<byte[]>("FilePDF")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LoaiBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaoCao");

                    b.ToTable("BaoCaos");
                });

            modelBuilder.Entity("LibraryApi.Models.BaoCaoViPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiViPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDocGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayTre")
                        .HasColumnType("int");

                    b.Property<string>("TenDocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BaoCaoViPhams");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_KiemKe", b =>
                {
                    b.Property<int>("MaPhieuKK")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int?>("ChenhLech")
                        .HasColumnType("int");

                    b.Property<int>("PhieuKiemKeId")
                        .HasColumnType("int");

                    b.Property<int?>("SL_HeThong")
                        .HasColumnType("int");

                    b.Property<int?>("SL_ThucTe")
                        .HasColumnType("int");

                    b.Property<int>("SachMaSach")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuKK", "MaSach");

                    b.HasIndex("PhieuKiemKeId");

                    b.HasIndex("SachMaSach");

                    b.ToTable("CT_KiemKe");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuMuon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CT_PhieuMuons");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_PhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoNgayMuon")
                        .HasColumnType("int");

                    b.Property<decimal?>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuTra", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CT_PhieuTras");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietDeXuatMuaSach", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDeXuat")
                        .HasColumnType("int");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDeXuat");

                    b.ToTable("ChiTietDeXuatMuaSachs");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietPhieuKiemKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChenhLech")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("PhieuKiemKeId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHeThong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongThucTe")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaSach");

                    b.HasIndex("PhieuKiemKeId");

                    b.ToTable("ChiTietPhieuKiemKes");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhieuNhapKhoId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapKhoId");

                    b.ToTable("ChiTietPhieuNhapKhos");
                });

            modelBuilder.Entity("LibraryApi.Models.DocGia", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDG"));

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKhoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiThanhVien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLanGiaHanToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayGiaHan")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayKhoa")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayMuonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoSachToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDG");

                    b.ToTable("DocGias");
                });

            modelBuilder.Entity("LibraryApi.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaND"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocGiaId")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaND");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("LibraryApi.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaNK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNK"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNK");

                    b.HasIndex("MaND");

                    b.ToTable("NhatKyHoatDongs");
                });

            modelBuilder.Entity("LibraryApi.Models.PhanHoiNCC", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<DateTime?>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu");

                    b.ToTable("PhanHoiNCCs");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuCapQuyen", b =>
                {
                    b.Property<int>("MaPhieuQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuQuyen"));

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<string>("QuyenDuocCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuQuyen");

                    b.HasIndex("MaND");

                    b.ToTable("PhieuCapQuyens");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuDatTruoc", b =>
                {
                    b.Property<int>("MaPhieuDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuDat"));

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuDat");

                    b.HasIndex("MaDG");

                    b.HasIndex("MaSach");

                    b.ToTable("PhieuDatTruocs");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuDeXuatMuaSach", b =>
                {
                    b.Property<int>("MaDeXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeXuat"));

                    b.Property<decimal>("ChiPhiDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDoTuChoi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaNguoiDeXuat")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MucDoUuTien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDeXuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SachMaSach")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDeXuat");

                    b.HasIndex("MaNguoiDeXuat");

                    b.HasIndex("MaNguoiDuyet");

                    b.HasIndex("SachMaSach");

                    b.ToTable("PhieuDeXuatMuaSachs");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuGiaHan", b =>
                {
                    b.Property<int>("MaGiaHan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaHan"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanGiaHan")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTuChoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHanCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHanMoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNgayGiaHan")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGiaHan");

                    b.HasIndex("MaDG");

                    b.HasIndex("MaPhieuMuon");

                    b.HasIndex("MaSach");

                    b.ToTable("PhieuGiaHans");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuKiemKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KyKiemKe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKiemKe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PhieuKiemKes");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"));

                    b.Property<int?>("DocGiaMaDG")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("DocGiaMaDG");

                    b.HasIndex("MaDG");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PhieuNhapKhos");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuPhat", b =>
                {
                    b.Property<int>("MaPhieuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuPhat"));

                    b.Property<string>("LoaiPhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuPhat");

                    b.HasIndex("MaDG");

                    b.ToTable("PhieuPhats");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuThu", b =>
                {
                    b.Property<int>("MaPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThu"));

                    b.Property<int>("BaoCaoViPhamId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiThu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiViPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaBaoCaoViPham")
                        .HasColumnType("int");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int?>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhieuMuonMaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("SachMaSach")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayTre")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuThu");

                    b.HasIndex("BaoCaoViPhamId");

                    b.HasIndex("MaDG");

                    b.HasIndex("PhieuMuonMaPhieuMuon");

                    b.HasIndex("SachMaSach");

                    b.ToTable("PhieuThus");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuTra"));

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuTra");

                    b.HasIndex("MaDG");

                    b.HasIndex("MaPhieuMuon");

                    b.ToTable("PhieuTras");
                });

            modelBuilder.Entity("LibraryApi.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaSach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamXB")
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriLuuTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Saches");
                });

            modelBuilder.Entity("LibraryApi.Models.TheThuVien", b =>
                {
                    b.Property<int>("MaThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThe"));

                    b.Property<string>("LoaiThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDK")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThe");

                    b.HasIndex("MaDG")
                        .IsUnique();

                    b.ToTable("TheThuViens");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_KiemKe", b =>
                {
                    b.HasOne("LibraryApi.Models.PhieuKiemKe", "PhieuKiemKe")
                        .WithMany()
                        .HasForeignKey("PhieuKiemKeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("SachMaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuKiemKe");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_PhieuMuon", b =>
                {
                    b.HasOne("LibraryApi.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("CT_PhieuMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany("CT_PhieuMuons")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.CT_PhieuTra", b =>
                {
                    b.HasOne("LibraryApi.Models.PhieuTra", "PhieuTra")
                        .WithMany("CT_PhieuTras")
                        .HasForeignKey("MaPhieuTra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany("CT_PhieuTras")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuTra");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietDeXuatMuaSach", b =>
                {
                    b.HasOne("LibraryApi.Models.PhieuDeXuatMuaSach", "PhieuDeXuatMuaSach")
                        .WithMany("ChiTietDeXuatMuaSachs")
                        .HasForeignKey("MaDeXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDeXuatMuaSach");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietPhieuKiemKe", b =>
                {
                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany("ChiTietPhieuKiemKes")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.PhieuKiemKe", "PhieuKiemKe")
                        .WithMany("ChiTietPhieuKiemKe")
                        .HasForeignKey("PhieuKiemKeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuKiemKe");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.HasOne("LibraryApi.Models.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany("ChiTietPhieuNhapKho")
                        .HasForeignKey("PhieuNhapKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapKho");
                });

            modelBuilder.Entity("LibraryApi.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("LibraryApi.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHoatDongs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuCapQuyen", b =>
                {
                    b.HasOne("LibraryApi.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhieuCapQuyens")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuDatTruoc", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuDatTruocs")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany("PhieuDatTruocs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuDeXuatMuaSach", b =>
                {
                    b.HasOne("LibraryApi.Models.NguoiDung", "NguoiDeXuat")
                        .WithMany()
                        .HasForeignKey("MaNguoiDeXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet");

                    b.HasOne("LibraryApi.Models.Sach", null)
                        .WithMany("PhieuDeXuatMuaSachs")
                        .HasForeignKey("SachMaSach");

                    b.Navigation("NguoiDeXuat");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuGiaHan", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuGiaHans")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuGiaHans")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany("PhieuGiaHans")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuMuon", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", null)
                        .WithMany("PhieuMus")
                        .HasForeignKey("DocGiaMaDG");

                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuPhat", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuPhats")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuThu", b =>
                {
                    b.HasOne("LibraryApi.Models.BaoCaoViPham", "BaoCaoViPham")
                        .WithMany()
                        .HasForeignKey("BaoCaoViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuThus")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.PhieuMuon", "PhieuMuon")
                        .WithMany()
                        .HasForeignKey("PhieuMuonMaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("SachMaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoCaoViPham");

                    b.Navigation("DocGia");

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuTra", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithMany("PhieuTras")
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuTras")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocGia");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryApi.Models.TheThuVien", b =>
                {
                    b.HasOne("LibraryApi.Models.DocGia", "DocGia")
                        .WithOne("TheThuVien")
                        .HasForeignKey("LibraryApi.Models.TheThuVien", "MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("LibraryApi.Models.DocGia", b =>
                {
                    b.Navigation("PhieuDatTruocs");

                    b.Navigation("PhieuGiaHans");

                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuMus");

                    b.Navigation("PhieuPhats");

                    b.Navigation("PhieuThus");

                    b.Navigation("PhieuTras");

                    b.Navigation("TheThuVien")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryApi.Models.NguoiDung", b =>
                {
                    b.Navigation("NhatKyHoatDongs");

                    b.Navigation("PhieuCapQuyens");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuDeXuatMuaSach", b =>
                {
                    b.Navigation("ChiTietDeXuatMuaSachs");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuKiemKe", b =>
                {
                    b.Navigation("ChiTietPhieuKiemKe");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuMuon", b =>
                {
                    b.Navigation("CT_PhieuMuons");

                    b.Navigation("PhieuGiaHans");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhapKho");
                });

            modelBuilder.Entity("LibraryApi.Models.PhieuTra", b =>
                {
                    b.Navigation("CT_PhieuTras");
                });

            modelBuilder.Entity("LibraryApi.Models.Sach", b =>
                {
                    b.Navigation("CT_PhieuMuons");

                    b.Navigation("CT_PhieuTras");

                    b.Navigation("ChiTietPhieuKiemKes");

                    b.Navigation("PhieuDatTruocs");

                    b.Navigation("PhieuDeXuatMuaSachs");

                    b.Navigation("PhieuGiaHans");
                });
#pragma warning restore 612, 618
        }
    }
}
